import "./style/normolize.css";
import "./style/base.css";
import "./style/header.css";
import "./style/main.css";
import "./style/brands.css";
import "./style/providers-news.css";
import "./style/recommend.css";
import "./style/about.css";
import "./style/footer.css";
import "./components/header.js"
import "./components/header-menu-catalogue.js"
import "./components/main-offers.js"
import "./components/brands.js"
import "./components/footer-mobile.js"
import "./components/swiper-slider.js"
